Trong bài này, chúng ta sẽ sử dụng file student.csv trong thư mục data và làm các ví dụ với file này

# Đọc dữ liệu

In [27]:
import pandas as pd

# Đọc dữ liệu từ file CSV
df = pd.read_csv('./data/student.csv')
# in ra 5 dòng đầu tiên
print(df.head(2))

   id            name               nationality           city  latitude  \
0   0       Kiana Lor                     China         Suzhou     31.31
1   1  Joshua Lonaker  United States of America  Santa Clarita     34.39

   longitude gender  ethnic.group  age  english.grade  math.grade  \
0     120.62      F           NaN   22            3.5         3.7
1    -118.54      M           NaN   22            2.9         3.2

   sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
0             3.1             1.0                 4                 4.0
1             3.6             5.0                 5                 4.0

   refletter.rating
0                 4
1                 5

In [28]:
df

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,Dane Whittemore,Vietnam,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5

# Khám phá dữ liệu

In [6]:
# Kiểm tra kiểu dữ liệu và thông tin chung
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  307 non-null    int64
 1   name                307 non-null    object
 2   nationality         307 non-null    object
 3   city                307 non-null    object
 4   latitude            307 non-null    float64
 5   longitude           307 non-null    float64
 6   gender              307 non-null    object
 7   ethnic.group        0 non-null      float64
 8   age                 307 non-null    int64
 9   english.grade       307 non-null    float64
 10  math.grade          307 non-null    float64
 11  sciences.grade      307 non-null    float64
 12  language.grade      307 non-null    float64
 13  portfolio.rating    307 non-null    int64
 14  coverletter.rating  307 non-null    float64
 15  refletter.rating    307 non-null    int64
dtypes: float64(8), int64(4), object(4)
memory usage: 38.5+ KB
None

In [8]:
# Xem thống kê mô tả của các cột số
df.describe()

,id,latitude,longitude,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
count,307.000000,307.000000,307.000000,0.0,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,153.000000,32.863388,-64.539121,NaN,21.964169,3.369707,3.414332,3.446580,4.396417,3.986971,4.110749,4.188925
std,88.767487,13.498582,81.249146,NaN,1.248013,0.538724,0.476839,0.509081,0.996474,0.928749,0.823936,0.842193
min,0.000000,-33.450000,-123.130000,NaN,19.000000,1.500000,2.100000,1.400000,1.000000,1.000000,1.000000,1.000000
25%,76.500000,32.720000,-118.240000,NaN,21.000000,3.100000,3.100000,3.200000,4.000000,3.500000,4.000000,4.000000
50%,153.000000,34.390000,-99.140000,NaN,22.000000,3.500000,3.500000,3.600000,5.000000,4.000000,4.000000,4.000000
75%,229.500000,38.960000,-73.855000,NaN,23.000000,3.800000,3.800000,3.800000,5.000000,5.000000,5.000000,5.000000
max,306.000000,59.890000,139.750000,NaN,26.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000

In [10]:
df['gender'].value_counts()

gender
F        152
M        151
other      4
Name: count, dtype: int64

In [9]:
nationality_counts = df['nationality'].value_counts()
nationality_counts

nationality
United States of America    193
Mexico                       24
China                        13
Japan                        13
Brazil                        9
India                         8
Canada                        7
Russian Federation            6
Colombia                      5
Korea (Republic of)           3
Pakistan                      3
Spain                         2
Turkey                        2
United Kingdom                2
Dominican Republic            1
Bangladesh                    1
Thailand                      1
Chile                         1
Netherlands                   1
Morocco                       1
Ukraine                       1
Egypt                         1
El Salvador                   1
Germany                       1
Peru                          1
Philippines                   1
Myanmar                       1
Tunisia                       1
Cuba                          1
Poland                        1
Nicaragua                     1
Name: count, dtype: int64

# Tìm giá trị lớn nhất/nhỏ nhất

In [16]:
df['english.grade'].mean()

3.3697068403908794

In [19]:
# Tìm học sinh có điểm English cao nhất
highest_english_grade = df['english.grade'].max()
print(highest_english_grade)
student_with_highest_english_grade = df[df['english.grade'] == highest_english_grade]
print(student_with_highest_english_grade[['name', 'english.grade']])

4.0
                    name  english.grade
15         Brittany Sath            4.0
68       Gabrielle Smith            4.0
120        Meghan Arnold            4.0
123       Gareth Newkirk            4.0
140         Faviola Soto            4.0
174        Andrew Bishop            4.0
181  Addie Villavicencio            4.0
195         Joshua Mesan            4.0
197           Troy White            4.0
201          Tyler Kibel            4.0
227    Patricia Rockhold            4.0
229     Katherine Beatty            4.0
240        Rylee Onstott            4.0
246    Vittoria Faulkner            4.0
268     Bryant Ronquillo            4.0
269         Garrett Heim            4.0
275       Blake Loughran            4.0
286      Michael Griffin            4.0

# Lọc dữ liệu

Các toán tử trong pandas
- `|`: or
- `&`: and
- `~`: not

In [23]:
filtered_df = df[(df['english.grade'] > 3.0) | (df['math.grade'] > 3.2)]
print(filtered_df[['name', 'english.grade', 'math.grade']])

                  name  english.grade  math.grade
0            Kiana Lor            3.5         3.7
2        Dakota Blanco            3.9         3.8
3      Natasha Yarusso            3.3         2.8
4       Brooke Cazares            3.7         2.6
5     Rochelle Johnson            3.4         3.1
..                 ...            ...         ...
301   Vanessa Gonzalez            3.3         3.7
302        Austin Haas            3.6         3.7
303    Madison Fithian            3.6         3.9
304  Zachary Mulvahill            3.2         3.4
306    Dane Whittemore            3.8         3.2

[286 rows x 3 columns]

In [33]:
filtered_df = df[(df['gender'] == 'M') & (df['nationality'] == 'Vietnam')]
print(filtered_df[['name', 'gender', 'nationality']])

                name gender nationality
306  Dane Whittemore      M     Vietnam

In [35]:
filtered_df = df[~(df['nationality'] == 'United States of America')]
print(filtered_df[['name', 'nationality']])

                      name  nationality
0                Kiana Lor        China
4           Brooke Cazares       Brazil
6               Joey Abreu        China
7           Preston Suarez       Brazil
8                 Lee Dong  Philippines
..                     ...          ...
285  Viridiana Ballesteros       Brazil
293      Taryn Springfield       Canada
296     Brittany Fernandez       Mexico
301       Vanessa Gonzalez    Nicaragua
306        Dane Whittemore      Vietnam

[114 rows x 2 columns]

In [39]:
df[['math.grade', 'sciences.grade', 'language.grade','language.grade']].mean(axis=0)

math.grade        4.0
sciences.grade    4.0
language.grade    5.0
language.grade    5.0
dtype: float64

In [41]:
df[['math.grade', 'sciences.grade', 'language.grade','language.grade']].mean(axis=1)

0      3.7
1      5.0
2      5.0
3      5.0
4      3.4
      ...
302    5.0
303    5.0
304    5.0
305    5.0
306    5.0
Length: 307, dtype: float64

In [52]:
# Kết hợp nhiều điều kiện
filtered_df = df[(df['gender'] == 'M') & (df['age'] > 18) & (df[['math.grade', 'sciences.grade', 'language.grade','language.grade']].mean(axis=1) > 3.5)]
print(filtered_df[['name', 'age', 'gender', 'math.grade', 'sciences.grade', 'language.grade']])

                     name  age gender  math.grade  sciences.grade  \
1          Joshua Lonaker   22      M         3.2             3.6
12      Alexander Sherman   20      M         3.6             3.9
13          Edgar Sanchez   23      M         3.5             4.0
14           Kolbi Strunk   21      M         3.9             3.3
18             David Pulc   24      M         2.9             4.0
..                    ...  ...    ...         ...             ...
298          Nicolas Papp   23      M         3.7             3.9
299  Christopher Inhulsen   23      M         3.3             2.9
302           Austin Haas   20      M         3.7             3.1
304     Zachary Mulvahill   20      M         3.4             3.9
306       Dane Whittemore   21      M         3.2             4.0

     language.grade
1               5.0
12              5.0
13              4.0
14              5.0
18              5.0
..              ...
298             5.0
299             5.0
302             5.0
304             5.0
306             5.0

[125 rows x 6 columns]

In [57]:
df[['math.grade', 'sciences.grade', 'language.grade','language.grade']].mean(axis=0)

math.grade        3.414332
sciences.grade    3.446580
language.grade    4.396417
language.grade    4.396417
dtype: float64

# Group By - df.groupby()

Dùng để chia df thành từng nhóm và tổng hợp giá trị. Các hàm thường dùng

- mean(): Tính giá trị trung bình của mỗi nhóm.
- sum(): Tính tổng của mỗi nhóm.
- count(): Đếm số lượng phần tử trong mỗi nhóm.
- max(): Tìm giá trị lớn nhất của mỗi nhóm.
- min(): Tìm giá trị nhỏ nhất của mỗi nhóm.
- std(): Tính độ lệch chuẩn của mỗi nhóm.
- median(): Tính giá trị trung vị của mỗi nhóm.
- agg(): Áp dụng nhiều hàm tổng hợp khác nhau lên mỗi nhóm.

In [42]:
grouped = df.groupby('nationality')
print(type(grouped))
print(grouped.groups)

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
{'Bangladesh': [146], 'Brazil': [4, 7, 96, 135, 180, 203, 226, 271, 285], 'Canada': [18, 104, 111, 121, 139, 293], 'Chile': [211], 'China': [0, 6, 21, 24, 61, 76, 162, 176, 189, 194, 214, 218, 232], 'Colombia': [94, 183, 185, 244, 283], 'Cuba': [70], 'Dominican Republic': [29], 'Egypt': [150], 'El Salvador': [105], 'Germany': [128], 'India': [35, 41, 72, 172, 175, 198, 215, 259], 'Japan': [15, 20, 37, 43, 46, 79, 95, 97, 99, 164, 200, 264, 280], 'Korea (Republic of)': [68, 213, 251], 'Mexico': [13, 17, 39, 49, 50, 82, 87, 112, 117, 125, 140, 141, 145, 148, 169, 178, 188, 191, 210, 236, 237, 265, 268, 296], 'Morocco': [187], 'Myanmar': [85], 'Netherlands': [190], 'Nicaragua': [301], 'Pakistan': [23, 59, 101], 'Peru': [36], 'Philippines': [8], 'Poland': [65], 'Russian Federation': [42, 93, 120, 134, 177, 217], 'Spain': [52, 129], 'Thailand': [234], 'Tunisia': [77], 'Turkey': [9, 171], 'Ukraine': [165], 'United Kingdom': [173, 230], 'United States of America': [1, 2, 3, 5, 10, 11, 12, 14, 16, 19, 22, 25, 26, 27, 28, 30, 31, 32, 33, 34, 38, 40, 44, 45, 47, 48, 51, 53, 54, 55, 56, 57, 58, 60, 62, 63, 64, 66, 67, 69, 71, 73, 74, 75, 78, 80, 81, 83, 84, 86, 88, 89, 90, 91, 92, 98, 100, 102, 103, 106, 107, 108, 109, 110, 113, 114, 115, 116, 118, 119, 122, 123, 124, 126, 127, 130, 131, 132, 133, 136, 137, 138, 142, 143, 144, 147, 149, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 163, 166, ...], 'Vietnam': [306]}

In [15]:
print(df.iloc[146])

id                                 146
name                  Juhaina al-Bilal
nationality                 Bangladesh
city                             Dhaka
latitude                         23.72
longitude                        90.41
gender                               F
ethnic.group                       NaN
age                                 20
english.grade                      3.9
math.grade                         3.9
sciences.grade                     3.9
language.grade                     5.0
portfolio.rating                     5
coverletter.rating                 4.0
refletter.rating                     5
Name: 146, dtype: object

In [45]:
print(grouped.get_group('China'))

      id              name nationality       city  latitude  longitude gender  \
0      0         Kiana Lor       China     Suzhou     31.31     120.62      F
6      6        Joey Abreu       China   Shenyang     41.79     123.43      M
21    21       David Weber       China     Peking     39.93     116.39      M
24    24       Sila Nguyen       China       Hebi     35.90     114.19      M
61    61      Colin Lemont       China   Shanghai     31.05     121.40      M
76    76  Sourinthone Tran       China      Wuhan     30.58     114.27      M
162  162    Rebecca Ah Fat       China   Tangshan     37.33     114.70      F
176  176          Surya Ky       China   Tangshan     37.33     114.70      M
189  189          Emma Kim       China   Hengshui     37.73     115.70      F
194  194  Chue Fue Richter       China    Qiqihar     47.34     123.97      M
214  214    Christian Chow       China     Handan     36.57     114.53      M
218  218     Nicole Patria       China  Chongqing     29.56     106.55      F
232  232    Anna Yoshimura       China     Rizhao     35.39     119.55      F

     ethnic.group  age  english.grade  math.grade  sciences.grade  \
0             NaN   22            3.5         3.7             3.1
6             NaN   22            3.7         3.9             3.6
21            NaN   20            3.9         3.9             3.9
24            NaN   23            2.8         3.5             3.5
61            NaN   21            3.6         4.0             3.1
76            NaN   21            3.5         3.9             3.4
162           NaN   22            1.8         3.8             4.0
176           NaN   21            3.7         4.0             3.8
189           NaN   22            2.8         3.9             3.8
194           NaN   23            3.0         3.6             1.4
214           NaN   21            2.6         3.9             3.4
218           NaN   24            3.9         3.3             3.0
232           NaN   20            3.5         3.8             3.9

     language.grade  portfolio.rating  coverletter.rating  refletter.rating
0               1.0                 4                 4.0                 4
6               2.0                 5                 5.0                 5
21              2.0                 3                 4.0                 5
24              4.0                 5                 4.0                 4
61              4.0                 4                 5.0                 4
76              4.0                 4                 4.0                 5
162             4.0                 4                 3.0                 4
176             4.0                 4                 4.0                 5
189             2.0                 4                 4.0                 4
194             4.0                 5                 3.0                 4
214             4.0                 5                 5.0                 5
218             2.0                 3                 5.0                 5
232             4.0                 5                 5.0                 2

In [47]:
grouped = df.groupby('nationality')[['english.grade', 'math.grade', 'sciences.grade', 'language.grade']]
grouped

In [49]:

# Tính điểm trung bình của các môn học theo quốc tịch
average_grades_by_nationality = df.groupby('nationality')[['english.grade', 'math.grade', 'sciences.grade', 'language.grade']].agg(['mean','max','min'])
print(average_grades_by_nationality)

                         english.grade           math.grade            \
                                  mean  max  min       mean  max  min
nationality
Bangladesh                    3.900000  3.9  3.9   3.900000  3.9  3.9
Brazil                        3.577778  3.9  2.8   3.377778  3.8  2.6
Canada                        3.633333  3.9  3.2   2.983333  3.7  2.3
Chile                         3.700000  3.7  3.7   3.700000  3.7  3.7
China                         3.253846  3.9  1.8   3.784615  4.0  3.3
Colombia                      3.540000  3.9  2.6   3.580000  4.0  3.0
Cuba                          3.900000  3.9  3.9   2.800000  2.8  2.8
Dominican Republic            3.400000  3.4  3.4   3.800000  3.8  3.8
Egypt                         1.500000  1.5  1.5   3.500000  3.5  3.5
El Salvador                   3.300000  3.3  3.3   2.900000  2.9  2.9
Germany                       3.200000  3.2  3.2   3.500000  3.5  3.5
India                         3.000000  3.9  1.7   3.275000  3.8  2.4
Japan                         3.330769  4.0  2.2   3.538462  4.0  2.9
Korea (Republic of)           3.533333  4.0  3.1   3.066667  3.5  2.7
Mexico                        3.358333  4.0  2.1   3.387500  4.0  2.3
Morocco                       2.400000  2.4  2.4   3.600000  3.6  3.6
Myanmar                       3.100000  3.1  3.1   3.400000  3.4  3.4
Netherlands                   2.500000  2.5  2.5   3.500000  3.5  3.5
Nicaragua                     3.300000  3.3  3.3   3.700000  3.7  3.7
Pakistan                      3.400000  3.8  3.1   2.933333  3.9  2.1
Peru                          3.700000  3.7  3.7   3.100000  3.1  3.1
Philippines                   3.900000  3.9  3.9   3.600000  3.6  3.6
Poland                        3.900000  3.9  3.9   3.800000  3.8  3.8
Russian Federation            3.550000  4.0  2.0   3.383333  3.9  2.5
Spain                         3.450000  3.5  3.4   3.750000  4.0  3.5
Thailand                      3.300000  3.3  3.3   3.900000  3.9  3.9
Tunisia                       3.500000  3.5  3.5   3.100000  3.1  3.1
Turkey                        2.600000  2.8  2.4   2.700000  2.8  2.6
Ukraine                       3.100000  3.1  3.1   3.300000  3.3  3.3
United Kingdom                3.400000  3.6  3.2   3.150000  3.7  2.6
United States of America      3.379275  4.0  1.7   3.417098  4.0  2.1
Vietnam                       3.800000  3.8  3.8   3.200000  3.2  3.2

                         sciences.grade           language.grade
                                   mean  max  min           mean  max  min
nationality
Bangladesh                     3.900000  3.9  3.9       5.000000  5.0  5.0
Brazil                         3.055556  3.9  1.5       2.888889  4.0  1.0
Canada                         3.533333  4.0  2.6       5.000000  5.0  5.0
Chile                          4.000000  4.0  4.0       3.000000  3.0  3.0
China                          3.376923  4.0  1.4       3.153846  4.0  1.0
Colombia                       3.280000  3.9  2.2       3.200000  4.0  1.0
Cuba                           3.200000  3.2  3.2       3.000000  3.0  3.0
Dominican Republic             4.000000  4.0  4.0       4.000000  4.0  4.0
Egypt                          3.200000  3.2  3.2       3.000000  3.0  3.0
El Salvador                    3.500000  3.5  3.5       3.000000  3.0  3.0
Germany                        3.900000  3.9  3.9       3.000000  3.0  3.0
India                          3.637500  4.0  3.0       3.125000  4.0  2.0
Japan                          3.492308  3.9  2.9       3.384615  4.0  2.0
Korea (Republic of)            3.200000  3.6  2.8       2.666667  3.0  2.0
Mexico                         3.441667  4.0  2.5       3.445833  5.0  1.0
Morocco                        3.800000  3.8  3.8       3.000000  3.0  3.0
Myanmar                        3.700000  3.7  3.7       3.000000  3.0  3.0
Netherlands                    3.700000  3.7  3.7       4.000000  4.0  4.0
Nicaragua                      3.800000  3.8  3.8       3.000000  3.0  3.0
Pakistan                       3.333333  3.9  2.3       3.333333  4.0  2.0
Peru                           3.000000  3.0  3.0       3.000000  3.0  3.0
Philippines                    3.200000  3.2  3.2       2.000000  2.0  2.0
Poland                         3.000000  3.0  3.0       3.000000  3.0  3.0
Russian Federation             3.133333  4.0  2.2       3.500000  4.0  2.0
Spain                          3.400000  3.4  3.4       3.000000  4.0  2.0
Thailand                       3.900000  3.9  3.9       2.000000  2.0  2.0
Tunisia                        4.000000  4.0  4.0       4.000000  4.0  4.0
Turkey                         3.850000  3.9  3.8       3.000000  3.0  3.0
Ukraine                        3.900000  3.9  3.9       3.000000  3.0  3.0
United Kingdom                 3.200000  3.9  2.5       5.000000  5.0  5.0
United States of America       3.455959  4.0  1.5       5.000000  5.0  5.0
Vietnam                        4.000000  4.0  4.0       5.000000  5.0  5.0

In [51]:

# Đếm số lượng học sinh theo thành phố và giới tính
student_count_by_city_gender = df.groupby(['nationality', 'gender'])['id'].count()
print(student_count_by_city_gender)

nationality               gender
Bangladesh                F           1
Brazil                    F           6
                          M           3
Canada                    F           3
                          M           2
                          other       1
Chile                     M           1
China                     F           5
                          M           8
Colombia                  F           1
                          M           4
Cuba                      F           1
Dominican Republic        F           1
Egypt                     M           1
El Salvador               F           1
Germany                   F           1
India                     F           5
                          M           3
Japan                     F           8
                          M           5
Korea (Republic of)       F           2
                          M           1
Mexico                    F          13
                          M          10
                          other       1
Morocco                   F           1
Myanmar                   F           1
Netherlands               F           1
Nicaragua                 F           1
Pakistan                  M           3
Peru                      M           1
Philippines               F           1
Poland                    M           1
Russian Federation        F           5
                          M           1
Spain                     M           2
Thailand                  F           1
Tunisia                   M           1
Turkey                    F           1
                          M           1
Ukraine                   M           1
United Kingdom            F           1
                          M           1
United States of America  F          91
                          M         100
                          other       2
Vietnam                   M           1
Name: id, dtype: int64

# sắp xếp df.sort_values
`sorted_df = df.sort_values(by='column', ascending=True)`

In [59]:
sorted_by_english = df.sort_values(by=['english.grade','math.grade'],ascending=[False,True])
print(sorted_by_english[['name', 'english.grade','math.grade']])

                       name  english.grade  math.grade
229        Katherine Beatty            4.0         2.4
68          Gabrielle Smith            4.0         3.0
275          Blake Loughran            4.0         3.0
123          Gareth Newkirk            4.0         3.2
201             Tyler Kibel            4.0         3.2
..                      ...            ...         ...
53           Moira Buttitto            1.9         2.8
162          Rebecca Ah Fat            1.8         3.8
41       Afnaan el-Mohammed            1.7         3.5
11             Sasha Jansen            1.7         4.0
150  Abdul Jabbaar el-Abdul            1.5         3.5

[307 rows x 3 columns]

# Bài tập
- Tìm 5 học sinh có điểm trung bình các môn học cao nhất.
- Tìm thành phố có nhiều học sinh nhất.
- Tạo một cột mới 'overall_rating' là trung bình cộng của 'portfolio.rating', 'coverletter.rating' và 'refletter.rating'.